# Merging Transportation data and Weather data

In [ ]:
import pandas as pd

In [ ]:
df_w = pd.read_csv('Weather.csv')

In [ ]:
df_w.head()

In [ ]:
df_w = df_w.drop('Date_time',1)

In [ ]:
df_w['Datetime'] = pd.to_datetime(df_w['date'].apply(str)+' '+df_w['time'])

In [ ]:
df_w.head()

         date  time  snow_cm  ...  humidity  pressure            Datetime
0  01.01.2019  0:00      0.2  ...        94      1030 2019-01-01 00:00:00
1  01.01.2019  1:00      0.2  ...        92      1029 2019-01-01 01:00:00
2  01.01.2019  2:00      0.2  ...        90      1028 2019-01-01 02:00:00
3  01.01.2019  3:00      0.2  ...        88      1028 2019-01-01 03:00:00
4  01.01.2019  4:00      0.2  ...        87      1027 2019-01-01 04:00:00

[5 rows x 11 columns]

In [ ]:
df_w.to_csv('Weather_final.csv', index=False)

In [ ]:
df_bus = pd.read_csv('/content/BusData_Delay_full.csv')

In [ ]:
df_bus.columns

Index(['Line', 'Pattern', 'Direction', 'Date', 'Stop', 'Stop.no', 'Sched..arr',
       'Actual.arr', 'Sched..dep', 'Actual.dep', 'Dwell.time', 'DT_actdpt',
       'DT_schdpt', 'delay_mins', 'delay'],
      dtype='object')

In [ ]:
df_bus['Datetime'] = pd.to_datetime(df_bus['DT_actdpt'])

In [ ]:
df_bus_c = df_bus.sort_values('Datetime')

In [ ]:
df_w_c = df_w.sort_values('Datetime')

In [ ]:
df = pd.merge_asof(df_bus_c, df_w_c, on='Datetime', direction= 'nearest')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2301243 entries, 0 to 2301242
Data columns (total 26 columns):
 #   Column         Dtype
---  ------         -----
 0   Line           int64
 1   Pattern        object
 2   Direction      int64
 3   Date           object
 4   Stop           object
 5   Stop.no        object
 6   Sched..arr     object
 7   Actual.arr     object
 8   Sched..dep     object
 9   Actual.dep     object
 10  Dwell.time     object
 11  DT_actdpt      object
 12  DT_schdpt      object
 13  delay_mins     float64
 14  delay          int64
 15  Datetime       datetime64[ns]
 16  date           object
 17  time           object
 18  snow_cm        float64
 19  wind_gusts     int64
 20  precipitation  float64
 21  temp           int64
 22  visibility     int64
 23  wind_speed     int64
 24  humidity       int64
 25  pressure       int64
dtypes: datetime64[ns](1), float64(3), int64(9), object(13)
memory usage: 474.0+ MB

In [ ]:
df.isnull().sum()

Line             0
Pattern          0
Direction        0
Date             0
Stop             0
Stop.no          0
Sched..arr       0
Actual.arr       0
Sched..dep       0
Actual.dep       0
Dwell.time       0
DT_actdpt        0
DT_schdpt        0
delay_mins       0
delay            0
Datetime         0
date             0
time             0
snow_cm          0
wind_gusts       0
precipitation    0
temp             0
visibility       0
wind_speed       0
humidity         0
pressure         0
dtype: int64

In [ ]:
df.to_csv('df_final.csv', index=False)

In [ ]:
df.head(20)

    Line                                            Pattern  ...  humidity pressure
0      6          6/159   Bornbreite -> Schöneberger Straße  ...        85     1025
1      8           8/253   Harzstraße -> Weender Straße-Ost  ...        85     1025
2      6          6/159   Bornbreite -> Schöneberger Straße  ...        85     1025
3      2  2/149   Friedhof Junkerberg -> Weender Straße-...  ...        85     1025
4      6  6/252   Schöneberger Straße -> Weender Straße-Ost  ...        85     1025
5      6  6/252   Schöneberger Straße -> Weender Straße-Ost  ...        85     1025
6      8           8/253   Harzstraße -> Weender Straße-Ost  ...        85     1025
7      2  2/149   Friedhof Junkerberg -> Weender Straße-...  ...        85     1025
8      6  6/252   Schöneberger Straße -> Weender Straße-Ost  ...        85     1025
9      8           8/253   Harzstraße -> Weender Straße-Ost  ...        85     1025
10     6  6/252   Schöneberger Straße -> Weender Straße-Ost  ...        85     1025
11     4       4/151   Auf der Lieth -> Weender Straße-West  ...        85     1025
12     2  2/149   Friedhof Junkerberg -> Weender Straße-...  ...        85     1025
13     4       4/151   Auf der Lieth -> Weender Straße-West  ...        85     1025
14     6  6/252   Schöneberger Straße -> Weender Straße-Ost  ...        85     1025
15     4       4/151   Auf der Lieth -> Weender Straße-West  ...        85     1025
16     2  2/149   Friedhof Junkerberg -> Weender Straße-...  ...        85     1025
17     8           8/253   Harzstraße -> Weender Straße-Ost  ...        86     1025
18     4       4/151   Auf der Lieth -> Weender Straße-West  ...        86     1025
19     8           8/253   Harzstraße -> Weender Straße-Ost  ...        86     1025

[20 rows x 26 columns]